### ISSUE TITLE
Option to reverse path and object - `selectn(obj, path)`

### ISSUE THREAD

**Issue by vjpr** [wilmoore/selectn#14]
Recent CoffeeScript to ES7 (Babel) convert right here...

Would be great to be able to reverse the params so its more natural, or CoffeeScript like.

E.g. In CoffeeScript:
```
feature?.properties?.length
```

This is what I envisage:
```
import s from 'selectn/alt'
s(feature, 'properties.length')
```

**Comment by wilmoore** [comment]
Hi @vjpr.

Thanks for the feature request. One of the original design decisions for this module (and most of my modules) is to put the most varying argument last.

You can read about why this is useful at the following URLs:

- http://stackoverflow.com/a/5863222/128346
- https://wiki.haskell.org/Parameter_order
