### ISSUE TITLE
Break the loop

### ISSUE THREAD

**Issue by filippomangione** [wilmoore/selectn#17]
A simple and yet great script.  
Is there a reason for not breaking the loop when an undefined value is encountered? 

```
for (; idx < len; idx += 1) {
  ref = ref[parts[idx]];
  if (ref === void 0) break;
}
```

It's just a very small optimization.

**Comment by wilmoore** [comment]
Hey @filippomangione -- That's awesome.

I was actually in the middle of a refactor. I have something that looks almost identical to this except that the `for` is now a `while` loop.

Yup, this will be in the next release.

Thanks man. I appreciate it!

**Comment by filippomangione** [comment]
@wilmoore Great!
